### ISSUE TITLE
Headless operation

### ISSUE THREAD

**Issue by philipp7pc** [rasmuskreiner/OSCVideo#4]
Dear Rasmus, discovered Your project this week and thinking about using the possibilities in a stage setup. 
Great work,

A question though: What would be the most elegant solution to "autostart" the Server at startup so the Raspberry boots directly into a blank black screen with the server ready, smb up and the osc port listening?

Thank You for a hint. 

Best 
Philipp

**Comment by philipp7pc** [comment]
never mind, can't use it anyways. doesn't seem to work.

**Comment by rasmuskreiner** [comment]
Hi Philip,

Sorry to hear that you didn't get it to work. FWIW the newest version of Raspberian has dropped support of omxplayer which this rely entirely on. Did you install from the image or clone from GitHub? Also keep in mind that the omxplayer is picky in terms of codecs and metadata. 

Starting up headless is somewhat straightforward. I'm Easter vacation - also hence the late reply - and do not have my computer with me so I cannot provide you with the command you could add to the crontab. If you still would like to give it a shot I'll get back Tuesday...?

Thanks!

**Comment by philipp7pc** [comment]
Hey Rasmus! Thanks for getting back and happy easter!

Yes I loaded the provided Image onto a RasPi 3B - without any updates or that, knowing that omx was going to be a problem in later versions of Raspian. 

I was testing with Your testfiles that run just fine if I run them over command line. 
After starting the Server I can without any problem turn on and off the background and run the Display test image commands from QLab. I'm using a Version3 QLab with all the cues copied. 
But sending the first or any OSC message in the Player methods group through the CueList kind of crashes the Server (It just won't react any more, but I can ssh reboot the raspberry or - if I undisplayed the background - restart the raspberry on it's own.)
Klicking the "send message" button in the QLab Cue settings directly gave me a result once, but didn't work after. 

After every attempt to alter the code or rename files or load my own files in different compressions and codec settings (vbr/cbr, higher or lower, mp4/m4v ...) I always reformatted the card with Your original Image. 

Thanks so much !

Talk to You next week. Now Happy Easter!
Philipp

**Comment by philipp7pc** [comment]
Good morning Rasmus!
Started playing around again. Found out that the main obstacle is my inability to display the terminal print for debugging. ;]

Second problem seems to be the "/load" method that seems to crash the server and then it won't accept any more osc messages. 

Is there a way to make OSCvideo ignore inconsistent messages instead of stalling? Would be good to be able to send a kill command or just "play next video - stop all previous".

**Comment by rasmuskreiner** [comment]
Hi Philip,

So I think I got a little bit closer as to why it was failing while loading. Small stupid typo!

Futhermore I’ve altered the code so it now prints to the console. I would recommend changing it back at showtime. It’s fairly easy: Just change line 15 to False. That said the code will send the same messages via OSC back to QLab, and change the notes field of a cue named “console”. This does not work if you have password protection on incoming OSC messages.

To start autostart in console, add the below to your crontab, and the server will start at boot time:

@reboot /usr/bin/python3 /home/pi/Documents/OSCvideo/main.py

Hope this helps!

Best,
Rasmus

**Comment by philipp7pc** [comment]
Thank You Rasmus!

Argh, brackets ! ;]

Thank You for the simple noob addition of the crontab hint. 
Could You keep both (line 15 and the crontab string) somewhere here as a documentation?

Going back to experimenting now.

EDIT: Still won't "load" a file into a player. 
>>> Sending Console message Error loading player. These arguements has been passed (1, b"/home/pi/Documents/OSCvideo/Static_files/Test_video_#4.m4v") - 192.168.178.71 - 53000 <<<

But it's fine as it is. I'm guessing it can be used without the /load command.

Do You think transitioning this script to vlc will be a big effort - to stay "up to date" with raspberry's strange decision of dropping media players?

Best
Philipp
